[build]
  publish = "dist"
  command = "bash scripts/build.sh"

[[redirects]]
  from = "/expenses"
  to = "/personal/expenses/"
  status = 301

[[redirects]]
  from = "/p/*"
  to = "/index.html"
  status = 200
